[package]
name = "my_swap_project"
version = "0.1.0"
authors = ["chetan yadav"]
description = "A token and token swap contract for the Aptos blockchain"



[addresses]
send_message = '0x71e1cec1cb979480c9bd8828fc3138986987f74ee63f8c479c924b948eca28ad'
[dev-addresses]

[dependencies.AptosFramework]
[dependencies]
MoveStdlib = { git = "https://github.com/aptos-labs/aptos-core", rev = "a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6q7r8s9t0" }

subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]

[workspace]
# Specify the path to the package
members = ["Token", "TokenSwap"]